name: CardsAgainstHerobrine
author: Nikl
main: me.nikl.cardsagainstherobrine.CardsAgainstHerobrine
version: 1.0.0
website: nikl.me
api-version: 1.13

commands:
  cardsagainstherobrine:
    description: test command
    usage: /test
    aliases: [cah]

permissions:
  cardsagainstherobrine.*:
    description: Gives all permissions
    children:
      cardsagainstherobrine.command.use: true
  cardsagainstherobrine.command.use:
    description: Allows usage of the wikipedia command
    default: true
